### ISSUE TITLE
Loading kernel driver

### ISSUE THREAD

**Issue by nerded1337** [hzqst/unicorn_pe#14]
I'm trying to use the emulator to unpack a kernel driver. When loading the sys file, BlackBone fails to map the image (it tries to load dependencies such as ntoskrnl -> werkenerl -> clfs etc...). Did I missed something ?

**Comment by hzqst** [comment]
Could you provide the kernel driver file you are trying to unpack?

**Comment by nerded1337** [comment]
It's vanguard anti-cheat from Valorant. I managed to get the emulator running it I still have issues. Can we go further on discord please ? nkp#9908
