### ISSUE TITLE
win10 1909 dependency on NToskrnl.exe failed to load  failed to MapImage

### ISSUE THREAD

**Issue by Akingg** [hzqst/unicorn_pe#25]
BlackBone: Allocate: Allocating at address 0x0000016844F30000 (0x1000 bytes)
BlackBone: Allocate: Allocating at address 0x0000016844F40000 (0x1000 bytes)
BlackBone: Allocate: Allocating at address 0x0000016844F50000 (0x4000 bytes)
BlackBone: ManualMap: Mapping image 'dump.XR.sys' with flags 0x1d001
BlackBone: ManualMap: Loading new image 'dump.XR.sys'
BlackBone: ManualMap: Image base allocated at 0x0000016846a60000
BlackBone: ManualMap: Performing image copy
BlackBone: ManualMap: Relocating image 'dump.xr.sys'
BlackBone: ManualMap: Loading new dependency 'ntoskrnl.exe'
BlackBone: ManualMap: Dependency path resolved to 'C:\WINDOWS\system32\ntoskrnl.exe'
BlackBone: ManualMap: Loading new image 'C:\WINDOWS\system32\ntoskrnl.exe'
BlackBone: ManualMap: Image base allocated at 0x0000016849be0000
BlackBone: ManualMap: Performing image copy
BlackBone: ManualMap: Relocating image 'c:\windows\system32\ntoskrnl.exe'
BlackBone: ManualMap: Loading new dependency 'werkernel.sys'
BlackBone: ManualMap: Dependency path resolved to 'werkernel.sys'
BlackBone: ManualMap: Loading new image 'werkernel.sys'
BlackBone: ManualMap: Image base allocated at 0x0000016845240000
BlackBone: ManualMap: Performing image copy
BlackBone: ManualMap: Relocating image 'werkernel.sys'
BlackBone: ManualMap: Loading new dependency 'ksecdd.sys'
BlackBone: ManualMap: Dependency path resolved to 'ksecdd.sys'
BlackBone: ManualMap: Loading new image 'ksecdd.sys'
BlackBone: ManualMap: Image base allocated at 0x0000016845260000
BlackBone: ManualMap: Performing image copy
BlackBone: ManualMap: Relocating image 'ksecdd.sys'
BlackBone: ManualMap: Loading new dependency 'hal.dll'
BlackBone: ManualMap: Dependency path resolved to 'C:\WINDOWS\system32\hal.dll'
BlackBone: ManualMap: Loading new image 'C:\WINDOWS\system32\hal.dll'
BlackBone: ManualMap: Image base allocated at 0x0000016846b10000
BlackBone: ManualMap: Performing image copy
BlackBone: ManualMap: Relocating image 'c:\windows\system32\hal.dll'
BlackBone: ManualMap: Loading new dependency 'kdcom.dll'
BlackBone: ManualMap: Dependency path resolved to 'c:\windows\system32\kdcom.dll'
BlackBone: ManualMap: Loading new image 'c:\windows\system32\kdcom.dll'
BlackBone: ManualMap: Image base allocated at 0x0000016845290000
BlackBone: ManualMap: Performing image copy
BlackBone: ManualMap: Relocating image 'c:\windows\system32\kdcom.dll'
BlackBone: ManualMap: Performing security cookie initializtion for image 'kdcom.dll'
BlackBone: ManualMap: Loading new dependency 'pshed.dll'
BlackBone: ManualMap: Dependency path resolved to 'c:\windows\system32\pshed.dll'
BlackBone: ManualMap: Loading new image 'c:\windows\system32\pshed.dll'
BlackBone: ManualMap: Image base allocated at 0x0000016846d70000
BlackBone: ManualMap: Performing image copy
BlackBone: ManualMap: Relocating image 'c:\windows\system32\pshed.dll'
BlackBone: ManualMap: Performing security cookie initializtion for image 'pshed.dll'
BlackBone: ManualMap: Performing security cookie initializtion for image 'hal.dll'
BlackBone: ManualMap: Loading new dependency 'msrpc.sys'
BlackBone: ManualMap: Dependency path resolved to 'msrpc.sys'
BlackBone: ManualMap: Loading new image 'msrpc.sys'
BlackBone: ManualMap: Image base allocated at 0x000001684b310000
BlackBone: ManualMap: Performing image copy
BlackBone: ManualMap: Relocating image 'msrpc.sys'
BlackBone: ManualMap: Performing security cookie initializtion for image 'msrpc.sys'
BlackBone: ManualMap: Performing security cookie initializtion for image 'ksecdd.sys'
BlackBone: ManualMap: Performing security cookie initializtion for image 'werkernel.sys'
BlackBone: ManualMap: Loading new dependency 'tm.sys'
BlackBone: ManualMap: Dependency path resolved to 'tm.sys'
BlackBone: ManualMap: Loading new image 'tm.sys'
BlackBone: ManualMap: Image base allocated at 0x000001684b640000
BlackBone: ManualMap: Performing image copy
BlackBone: ManualMap: Relocating image 'tm.sys'
BlackBone: ManualMap: Loading new dependency 'clfs.sys'
BlackBone: ManualMap: Dependency path resolved to 'clfs.sys'
BlackBone: ManualMap: Loading new image 'clfs.sys'
BlackBone: ManualMap: Image base allocated at 0x000001684b670000
BlackBone: ManualMap: Performing image copy
BlackBone: ManualMap: Relocating image 'clfs.sys'
BlackBone: ManualMap: Performing security cookie initializtion for image 'clfs.sys'
BlackBone: ManualMap: Performing security cookie initializtion for image 'tm.sys'
BlackBone: ManualMap: Failed to get import 'TraceInitSystem' from image 'ntoskrnl.exe'
BlackBone: Free: Free at address 0x0000016849BE0000
BlackBone: ManualMap: Failed to load dependency 'C:\WINDOWS\system32\ntoskrnl.exe'. Status 0xc0000225
BlackBone: Free: Free at address 0x0000016846A60000
BlackBone: Free: Free at address 0x0000016844F30000
BlackBone: Free: Free at address 0x0000016844F40000
BlackBone: Free: Free at address 0x0000016844F50000
failed to MapImage

**Comment by Akingg** [comment]
BlackBone: ManualMap: Failed to get import 'TraceInitSystem' from image 'ntoskrnl.exe'
BlackBone: ManualMap: Failed to load dependency 'C:\WINDOWS\system32\ntoskrnl.exe'. Status 0xc0000225

**Comment by hzqst** [comment]
Should be fixed with latest commit e7526f9.
