### ISSUE TITLE
The latest build has many errors

### ISSUE THREAD

**Issue by Akingg** [hzqst/unicorn_pe#26]
![FL`YMMMN9PS5Z)XZ`RLF(I9](https://user-images.githubusercontent.com/80285449/115681566-3cbf1400-a387-11eb-9489-03f156b8cb73.png)

**Comment by hzqst** [comment]
![QQ截图20210422173444](https://user-images.githubusercontent.com/12287588/115691902-0b4b4600-a391-11eb-9f7d-0a28e8ab44cc.png)
我这儿vs2017 直接git clone+编译 没发现问题

**Comment by Akingg** [comment]
> ![QQ截图20210422173444](https://user-images.githubusercontent.com/12287588/115691902-0b4b4600-a391-11eb-9f7d-0a28e8ab44cc.png)
> 我这儿vs2017 直接git clone+编译 没发现问题

已正常运行，非常感谢，祝您顺风顺水，财源广进，升官发财
